data.file=data/knowledge.json

fixedstrategy.questionIndex=1

question.selection.strategy=FIXED
#question.selection.strategy=SEQUENTIAL
#question.selection.strategy=RANDOM
#question.selection.strategy=ADAPTIVE
